import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
const HomePage = () => {
    const navigate = useNavigate();
    const handleLoginClick = () => {
        navigate('/login');
    };
    const handleSignUpClick = () => {
        navigate('/signup');
    };
    return (_jsx("div", { className: "flex min-h-screen w-screen bg-gray-100", children: _jsxs("div", { className: "flex flex-col flex-grow", children: [_jsx("header", { className: "bg-white shadow p-4 items-center", children: _jsxs("div", { className: "flex justify-end", children: [_jsx("button", { className: "bg-blue-700 text-white px-4 py-2 rounded-md mr-2 transition duration-300 ease-in-out hover:bg-white hover:text-blue-700 hover:border hover:border-blue-700", onClick: handleLoginClick, children: "\u0110\u0103ng nh\u1EADp" }), _jsx("button", { className: "bg-blue-700 text-white px-4 py-2 rounded-md transition duration-300 ease-in-out hover:bg-white hover:text-blue-700 hover:border hover:border-blue-700", onClick: handleSignUpClick, children: "\u0110\u0103ng k\u00FD" })] }) }), _jsxs("main", { className: " flex-col mt-10 pl-10", children: [_jsx("h2", { className: "text-gray-400 ml-1", children: "Anywhere and Everywhere" }), _jsx("h1", { className: "text-4xl font-bold text-blue-600 ", children: "Ch\u00E0o m\u1EEBng \u0111\u1EBFn v\u1EDBi" }), _jsx("h1", { className: "text-4xl font-bold text-blue-600 mb-4", children: "Tr\u01B0\u1EDDng Ti\u1EC3u H\u1ECDc Nam H\u00E0" }), _jsx("p", { className: "text-lg mb-2", children: "Theo d\u00F5i vi\u1EC7c \u0111\u1ECDc c\u1EE7a b\u1EA1n v\u00E0 x\u00E2y d\u1EF1ng th\u01B0 vi\u1EC7n c\u1EE7a b\u1EA1n." }), _jsx("p", { className: "text-lg", children: "Kh\u00E1m ph\u00E1 cu\u1ED1n s\u00E1ch y\u00EAu th\u00EDch c\u1EE7a b\u1EA1n." }), _jsx("p", { className: "text-lg", children: "Theo d\u00F5i ti\u1EBFn \u0111\u1ED9 \u0111\u1ECDc s\u00E1ch c\u1EE7a b\u1EA1n." }), _jsx("p", { className: "text-lg mb-3", children: "\u0110\u1ECDc s\u00E1ch m\u1ECDi l\u00FAc, m\u1ECDi n\u01A1i." }), _jsx("button", { onClick: handleLoginClick, className: "bg-blue-500 text-white px-6 py-3 rounded-md transition duration-300 ease-in-out hover:bg-white hover:text-blue-700 hover:border hover:border-blue-700", children: "B\u1EAFt \u0111\u1EA7u kh\u00E1m ph\u00E1" })] }), _jsxs("footer", { className: "bg-white py-4 w-full text-left text-sm absolute bottom-0 left-0 pl-10", children: [_jsx("h1", { className: "mb-2 font-bold text-blue-600 text-xl", children: "Th\u00F4ng tin li\u00EAn l\u1EA1c" }), _jsx("p", { children: "Email: test@gmail.com" }), _jsx("p", { children: "Zalo: 0377xxxxxx" }), _jsxs("div", { className: "flex justify-left space-x-4 mt-2 mb-2 text-blue-600", children: [_jsx("a", { href: "#", children: _jsx("i", { className: "fab fa-facebook" }) }), _jsx("a", { href: "#", children: _jsx("i", { className: "fab fa-twitter" }) }), _jsx("a", { href: "#", children: _jsx("i", { className: "fab fa-instagram" }) })] })] })] }) }));
};
export default HomePage;
